mykey = "devopskey"
ami = "ami-0947d2ba12ee1ff75"
region = "us-east-1"
instance_type = "t3a.medium"
jenkins_server_secgr = "jenkins-server-security-group"
jenkins_server_tag = "jenkins-server-profile"
jenkins_profile = "jenkins-server-profile"
jenkins_role = "jenkins-server-role"